#! /bin/bash
# -*- mode: shell-script -*-

tmp=/tmp/configtools.test.$$

mkdir -p $tmp

# trap "rm -rf $tmp" EXIT INT QUIT

ver=$(python -c 'import sys; print("%d.%d" % sys.version_info[:2])')
python setup.py build

# So *always* use the in-tree version of configtools here.
# prefix better be right at this point
if [[ ! -f build/scripts-$ver/getconf.py ]]
then
    echo "Cannot find getconf.py: build/scripts-$ver/getconf.py" 1>&2
    exit 1
fi

ppathins() {
    if [ -d "$1" ] && [[ ":$PYTHONPATH:" != *":$1:"* ]]; then
        PYTHONPATH="$1:$PYTHONPATH"
    fi
}

export PYTHONPATH
ppathins $PWD/build/lib

bin=$PWD/build/scripts-$ver

function run_test {
    testnum=$1
    shift
    dir=$1
    shift

    eval "$bin/$dir $*" > $tmp/test.out 2>&1

    echo Test $testnum
    if diff $tmp/test.out gold/$dir/$testnum.out ; then
        echo PASS
    else
        echo FAIL
    fi
}

run_test 1 getconf.py --config samples/foo.conf bar foo
run_test 2 getconf.py --config samples/foo.conf baz foo
run_test 3 getconf.py --config samples/foo.conf -a foo
run_test 4 getconf.py --config samples/foo.conf foo foo

run_test 1 gethosts.py --config samples/hosts.conf -a
run_test 2 gethosts.py --config samples/hosts.conf -c clients
run_test 3 gethosts.py --config samples/hosts.conf -c servers
run_test 4 gethosts.py --config samples/hosts.conf -L
